### ISSUE TITLE
Site improvements

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/jessesquires.com#1]
**Posts**
- [ ] categories
- [ ] tags
- [ ] related posts on post page
- [ ] prev/next on post page
- [x] search

**Other pages**
- [x] Archives page
- [x] About page

**Comment by muhasturk** [comment]
Disqus comment system will be useful for your site. BTW, I like it.

**Comment by jessesquires** [comment]
Closing in favor of #66 and #67
