### ISSUE TITLE
Xcode tip: Using breakpoints as bookmarks

### ISSUE THREAD

**Issue by robfeldmann** [jessesquires/jessesquires.com#103]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/xcode-tip-breakpoints-as-bookmarks/

This is exactly how I work too. One problem that I face, however, is I find my breakpoints can get shifted around a bit like they’re getting out of sync with the editor. I’m curious if you’ve experienced this also?

For example, they’ll start to appear several lines below where I initially placed them. This is especially the case as I’m writing new code or refactoring existing code. Sometimes a new build and run cycle will put them back to the correct place, but mostly I’m constantly putting them back where they belong manually.

**Comment by jessesquires** [comment]
Hey @robfeldmann ! Thanks for the comment 😄 

Yes, I have seen that, however it's usually because the code in a file has changed and the breakpoint is stuck at the original line number. Otherwise it seems pretty reliable, but I'll keep an eye out for that.

**Comment by robfeldmann** [comment]
At least I'm not alone. One of these days I'm going to file a bug. Thanks!
