### ISSUE TITLE
Implementing Dark Mode and using CGColor

### ISSUE THREAD

**Issue by LarryGensch** [jessesquires/jessesquires.com#104]
I think your article glosses over the derivation of a `CGColor` from a `UIColor`, and can lead to some confusion when some layer colors don't properly adapt...

```swift
public override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
    // ...
    view.layer.shadowColor = UIColor.systemGray.cgColor
}

```
The problem is with a` UIColor` that adapts to light and dark mode may have differing colors depending on the current `.userInterfaceStyle`, so using `.cgColor` by itself is a bit naive, since `UIColor` doesn't have access to the current trait collection.

To get the proper value, you need to pass the current trait collection to `UIColor` to resolve to the actual color that is desired:

`view.layer.shadowColor = UIColor.systemGray.resolved(with: traitCollection).cgColor`

That seems to be a bit long-winded, so (of course) Apple gave us a bit of a short cut:

```swift
traitCollection.performAsCurrent {
    view.layer.shadowColor = UIColor.systemGray.cgColor
    // other CGColor assignments as necessary
}
```

This is guaranteed to work properly.

You can refer to this from Apple's  Implementing Dark Mode in iOS session at WWDC 2019.

**Comment by jessesquires** [comment]
Hey @LarryGensch 👋 

Thank you so much for this! I will update the post soon!

**Comment by jessesquires** [comment]
I just tested this and it looks like even if you use `traitCollection.performAsCurrent()`, you still need to call this from within `traitCollectionDidChange()`.

Initially, I thought you could, for example, use `traitCollection.performAsCurrent()` in your initializer and it would automatically get triggered on trait collection changes, but that is not the case.

I think I'll leave the post as-is for now, but this is still great info.

Thanks again @LarryGensch ! 💯
