### ISSUE TITLE
Get the time depending to local time zone

### ISSUE THREAD

**Issue by hiworld75018** [jessesquires/jessesquires.com#112]
Hi Jesse,
Thank you for **Nine41**, that is a really nice job.

It would be great if time if set according to the local time zone (in Main.swift:55). My Mac time zone is Reykjavik/Iceland (UTC time), and simulator just shows "5:41".

Sorry that I am not "fluent" in swift, being an obj-c "old-timer"...
Philippe

**Comment by jessesquires** [comment]
Thanks for reporting this @hiworld75018 !

We are tracking the bug at https://github.com/jessesquires/Nine41/issues/10
