### ISSUE TITLE
Post "edit" links not working

### ISSUE THREAD

**Issue by hisaac** [jessesquires/jessesquires.com#117]
Hi Jesse. I just went to edit one of your posts using the "edit" link at the bottom of the page, but it points to the wrong location. I don't have time to dig into why at the moment, but figured I'd let you know about it.

An example: Clicking the "edit" button on [your post about [Quickly switching between Xcodes](https://www.jessesquires.com/blog/2020/07/07/quickly-switching-between-xcodes/) goes to this URL:

`https://github.com/jessesquires/jessesquires.com/edit/master/_posts/2020-07-07-20200707quickly-switching-between-xcodes.md`

When it should go to this URL:

`https://github.com/jessesquires/jessesquires.com/edit/master/_posts/2020-07-07-quickly-switching-between-xcodes.md`

Looks like the file name gets some extra numbers added to it for some reason.

**Comment by jessesquires** [comment]
Thanks for reporting this, @hisaac ! 💯 

> Looks like the file name gets some extra numbers added to it for some reason.

That's the date being repeated. 😊 

I'm pretty sure it broke because of this: https://www.jessesquires.com/blog/2020/04/15/updating-permalinks-and-adding-redirects-for-jekyll-sites/

I'll fix this soon.
