### ISSUE TITLE
Swift globals and static members are atomic and lazily computed

### ISSUE THREAD

**Issue by allenhsu** [jessesquires/jessesquires.com#118]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2020/07/16/swift-globals-and-static-members-are-atomic-and-lazily-computed/

Personally, I don't agree with the following statement:

> Given this, there are a few important things to note. The concept of atomicity is distinct from the concept of thread-safety. Atomicity does not imply thread-safety, but if something is thread-safe it must be atomic.

IMPO, since the modifier of atomic is on the property itself, it ensures the atomicity of the property, and the property is tread-safe. So atomicity does imply thread-safety. The following quote from the doc is not exactly meaning "atomicity does not imply thread-safety". Instead, it means "a properties's thread-safety cannot imply an object's thread-safety". They are slightly different. Actually any thread-safe classes/objects can be used in a thread-unsafe way, but it does not change the thread-safety of the class/object itself.

> **Note:** Property atomicity is not synonymous with an object’s thread safety.
> 
> Consider an `XYZPerson` object in which both a person’s first and last names are changed using atomic accessors from one thread. If another thread accesses both names at the same time, the atomic getter methods will return complete strings (without crashing), but there’s no guarantee that those values will be the right names relative to each other. If the first name is accessed before the change, but the last name is accessed after the change, you’ll end up with an inconsistent, mismatched pair of names.

Just my two cents.

**Comment by jessesquires** [comment]
Thanks @allenhsu ! 💯 

Sorry for such a delay. I will update the post soon!

**Comment by jessesquires** [comment]
Hey @allenhsu ! 👋 Actually, after reviewing this again, I have some thoughts/questions.

> Atomicity does not imply thread-safety, but if something is thread-safe it must be atomic.

I'm actually not naming anything specific here, but commenting on the relationship between these concepts. So I think this is still accurate.

For example, an object whose properties are *mutable* and atomic is not thread-safe, unless you use a lock to restrict/manage access to those properties across threads. However, if an object is thread-safe, then all of its properties must be thread-safe and atomic.

> Since the modifier of atomic is on the property itself, it ensures the atomicity of the property, and the property is tread-safe. 

I'm not sure if the concept of "thread-safe properties" is valuable, is it? If the entire object is not thread-safe, why would we care if a single property of an object is thread-safe? Or, in other words, for an object to be thread-safe, access to all of it's properties must be thread-safe.

> So atomicity does imply thread-safety. 

I don't think this is true. (See first explanation.)

> The following quote from the doc is not exactly meaning "atomicity does not imply thread-safety". Instead, it means "a properties's thread-safety cannot imply an object's thread-safety".

Yes! I do agree with this. 💯
