### ISSUE TITLE
Thank you for publishing "Enums as configuration: the anti-pattern"!

### ISSUE THREAD

**Issue by MarshalGeazipp** [jessesquires/jessesquires.com#124]
Hi Jesse, 

I came across your old [blog post](https://www.jessesquires.com/blog/2016/07/31/enums-as-configs/) today. I really like it and I think it is highly valuable. It inspired me to do some refactoring immediately 😄 . 
Thank you very much for this post and for all your blogging and open source work in general!
Please continue!

Regards,
Sebastian

**Comment by jessesquires** [comment]
Thanks so much @MarshalGeazipp ! 😄 🎉 

I'm glad it helped!
