### ISSUE TITLE
How to fix the incomprehensible tabs in Xcode 12

### ISSUE THREAD

**Issue by Jusung** [jessesquires/jessesquires.com#127]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2020/07/24/how-to-fix-the-incomprehensible-tabs-in-xcode-12/

Cool! It was very annoying.
You saved my days.

Thank you for sharing very useful information! 👍 😄

**Comment by jessesquires** [comment]
@Jusung glad it helped! 💯
