### ISSUE TITLE
Three months of Big Sur

### ISSUE THREAD

**Issue by galad87** [jessesquires/jessesquires.com#150]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2021/06/01/three-months-of-big-sur/

Books.app is not a Catalyst app ;)

**Comment by jessesquires** [comment]
Oh really? 😅 It sure seems like it. What's the best way to confirm that?

Thanks for letting me know @galad87! 💯

**Comment by galad87** [comment]
otool -L to see if it's linking UIKit, or lsof to check if it loads UIKitCore at runtime.

**Comment by jessesquires** [comment]
thanks again @galad87 ! 🙌🏼 

i have updated the post.
