### ISSUE TITLE
How to test an iOS Swift package without an Xcode project

### ISSUE THREAD

**Issue by HHuckebein** [jessesquires/jessesquires.com#158]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2021/11/03/swift-package-ios-tests/

Thanks for pointing this out. I had several spm framework project and all had an .xcodeproj file just for the CI.
Anyway. It seems though that -enableCodeCoverage YES doesn't generate anything. In the past I used this command 

xcrun llvm-cov export -format="lcov" .build/debug/**FrameworkName**PackageTests.xctest/Contents/MacOS/**FrameworkName**PackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov

to export coverage data but there are no default.profdata after running the tests.

**Comment by jessesquires** [comment]
Hey @HHuckebein -- yes, I have noticed this as well. This seems to be an unfortunate limitation. 😕

**Comment by jessesquires** [comment]
I've updated the original post to include this info. Thanks for pointing out @HHuckebein !

**Comment by jessesquires** [comment]
https://www.jessesquires.com/blog/2021/11/03/swift-package-ios-tests/#updated-17-november-2021
