### ISSUE TITLE
On third-party Apple Watch apps

### ISSUE THREAD

**Issue by mrrcollins** [jessesquires/jessesquires.com#159]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2022/01/11/on-third-party-apple-watch-apps/

Two apps that work well are Nano for Reddit and and Nanogram (Telegram messenger on the Watch). Both work as well as any of the Apple apps on the watch, and Nanogram works better than the official Telegram app.

Other than that, good watch apps are few and far between.

**Comment by jessesquires** [comment]
Thanks @mrrcollins !
