### ISSUE TITLE
My website disappeared from Bing and DuckDuckGo

### ISSUE THREAD

**Issue by behroozbc** [jessesquires/jessesquires.com#165]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2022/03/25/my-website-disappeared-from-bing-and-duckduckgo/
hi,
I have same problem with bing , but I find your website on bing!
how you fix your website?

**Comment by jessesquires** [comment]
hey @behroozbc! thanks for commenting. 😊 

I didn't do anything specific to make my site come back. I'll be writing a follow-up post soon.

For now, check out the existing discussion at #163

**Comment by jessesquires** [comment]
Finally published: https://www.jessesquires.com/blog/2022/07/25/my-website-disappeared-from-bing-and-duckduckgo-part-2/

**Comment by bikegremlin** [comment]
Same problem. I used the opportunity to investigate a bit and create a list of search engines that practically just copy Bing results/indexes (followed by a list of those that seem to be independent):
[](https://io.bikegremlin.com/28530/microsoft-bing-serp-gone-overnight/)

**Comment by imgeraldalinio** [comment]
@jessesquires I came across this thread thanks to your blog posts. I'm currently experiencing the same issue on my website https://linuxbeast.com/. Appreciate you sharing your experience.
