### ISSUE TITLE
My website disappeared from Bing and DuckDuckGo, Part 2

### ISSUE THREAD

**Issue by dougienisbet** [jessesquires/jessesquires.com#168]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2022/07/25/my-website-disappeared-from-bing-and-duckduckgo-part-2/

Really interesting blog posts and timeline. I found it after realising that my website was not being found on Bing or DuckDuckGo. I just tinker with a personal WordPress site - nothing to sell - just cats and the garden. Also, don't care about Bing, but would have liked to appear on DDG.

A couple of observations searching my domains using Bing. There definitely seems to be a difference between 'Nothing found' and the slightly sinister 'Some results might have been removed'. Here's two searches on domains that I have - both running WordPress on the same host.

My hobby website: katsura.uk
![Screenshot_20220821_143448 katsura bing](https://user-images.githubusercontent.com/5359681/185793571-e98bcefa-7200-479e-849b-007edc5d37da.png)

A test site for my running club: wetfeet.uk
![Screenshot_20220821_143518 wet feet](https://user-images.githubusercontent.com/5359681/185793595-812963be-ec2e-4c14-a3db-5f1c10fd6923.png)

Subtly different results. I'm baffled about what I've done on my katsura.uk that could be considered so subversive. But also, I'm not sure I can be bothered trying to find out.

**Comment by jessesquires** [comment]
Thanks for sharing @dougienisbet! I'm sorry you are also dealing with this problem.

Yes, I've also seen both of those types of results. 

It is truly baffling. Who knows what the fuck is going on over at Bing. 🤷🏼
