### ISSUE TITLE
My worst tech interview experience

### ISSUE THREAD

**Issue by Eric-Sunny-Fish** [jessesquires/jessesquires.com#172]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2021/12/01/my-worst-tech-interview-experience/

I had a very similar experience with the Watch team at Apple in March of 2019. They flew me out to interview me at the new headquarters. I had four sessions with different interviewers. Each session was with two or three members of the team. One of the sessions was a whiteboard coding test. The interviewers showed the same attitude you saw, which flustered me. I knew the answers, but couldn't get them out because I was nervous, angry, and trying desperately to hide those feelings. I did not get an offer.

Even if I had gotten an offer I doubt I would have accepted it. I found the environment beautiful, but way too distracting. I'm sure I would have failed working in the saucer.

**Comment by jessesquires** [comment]
Thanks for sharing @Eric-Sunny-Fish !

Sorry you also have a negative experience 😕
