### ISSUE TITLE
How to more gracefully handle non-optional Core Data properties in Swift

### ISSUE THREAD

**Issue by mecoFarid** [jessesquires/jessesquires.com#174]
Feedback: https://www.jessesquires.com/blog/2022/01/26/core-data-optionals/

To be honest, this just encourages cumbersome solutions which will result in more headache than one would think. I am 100% positive experience iOS devs would never approve of this in any way. I know there is no credible way but you are just making it even worse this goes for the post you are referencing in your post (https://atomicbird.com/blog/clash-of-the-optionals/).

This bug (or huge crap) makes whole Core Data useless. If they did not write this crap it would have been much better and probably would have encouraged open-sourcers to write something better

**Comment by jessesquires** [comment]
Thanks for the feedback @mecoFarid !

**Comment by mecoFarid** [comment]
I, for sure, sounded very rude but it only comes from my frustration that how come such a nicely done API would have such a big flaw which yields it useless. It was nothing personal towards you, just to be clear
