### ISSUE TITLE
Publishing an RSS feed to Mastodon

### ISSUE THREAD

**Issue by techjournalist** [jessesquires/jessesquires.com#177]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2022/12/15/rss-to-mastodon/

the URL for the status update https://mastodon.social/api/v1/statuses /   - does not seem to work anymore with IFTT. Also should the URL be changed based on the instance ?

**Comment by jessesquires** [comment]
Hey @techjournalist ! 👋🏼 

> the URL for the status update https://mastodon.social/api/v1/statuses / - does not seem to work anymore with IFTT. 

Sadly, this might be the problem: https://daringfireball.net/linked/2023/02/02/twitter-apis

> Also should the URL be changed based on the instance ?

Yes! You should use the URL for your instance.

**Comment by techjournalist** [comment]
Any ideas on how to make an RSS to Mastodon tool now with IFTT?
I've tried to do the same thing on Pipedream.com and ran into the same issue with the api...so i'm not sure it's IFTT specific. Happy to work with you to figure out what does work ...as this is a need that lots of ppl have.
