### ISSUE TITLE
Fix: eventmachine gem failed to build on macOS Ventura with Ruby 2.7.6

### ISSUE THREAD

**Issue by MeilinaR** [jessesquires/jessesquires.com#178]
Hi! Thanks for providing this tutorial to fix this bug. I've got the exact same error as you

```
An error occurred while installing eventmachine (1.2.7), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.2.7' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jekyll-archives was resolved to 2.2.1, which depends on
    jekyll was resolved to 4.3.2, which depends on
      em-websocket was resolved to 0.5.3, which depends on
        eventmachine
```

I tried to download eventmachine through the command you provided. Eventmachine managed to build, however when running ```bundle install``` and consequently ```bundle exec jekyll serve``` it says that Eventmachine cannot be found for some reason, even though I just downloaded it. Do you have any tips/suggestions how to solve this?

**Comment by jessesquires** [comment]
hey @MeilinaR ! 👋🏼 I'm glad this helped.

>  it says that Eventmachine cannot be found for some reason, even though I just downloaded it. Do you have any tips/suggestions how to solve this?

Hm... I'm not really sure, unfortunately. Does `bundle install` still fail? 

Are you using something like `rbenv` to manage ruby versions? Maybe you installed `eventmachine` in a different ruby version from where you installed `jekyll`?
