### ISSUE TITLE
Exploring a new iOS codebase

### ISSUE THREAD

**Issue by icanzilb** [jessesquires/jessesquires.com#182]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2023/04/04/exploring-a-new-ios-codebase/

I wrote about something similar around tracking views in SwiftUI and UIKit view controllers here https://trycombine.com/posts/code-samples-on-how-to-approach-debugging-swift-and-uikit-apps/ maybe it's interesting to have a look

**Comment by jessesquires** [comment]
Thanks @icanzilb! 🙌🏼
