### ISSUE TITLE
Publishing an RSS feed to Mastodon

### ISSUE THREAD

**Issue by wydwww** [jessesquires/jessesquires.com#183]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2022/12/15/rss-to-mastodon/

[Pipedream](https://pipedream.com/) provides a Webhook API in the free plan. I just tried setting up an app there following your blog and it works. But Zapier's processed RSS contents (e.g., separating images and texts in the `description` section) really help when making a Mastodon post.

**Comment by jessesquires** [comment]
Thanks @wydwww! 

I didn't know about Pipedream.
