### ISSUE TITLE
Going indie: business structure, taxes, and retirement

### ISSUE THREAD

**Issue by ljmatkins** [jessesquires/jessesquires.com#186]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2023/08/16/going-indie-3/

> Limited Liability Company (LLC). [IRS, Wiki] An LLC is what I know the least about, but my understanding is that it is even more formal than an S-Corp. It is an established business entity that you also have to file paperwork to legally setup, pay fees, get an EIN, etc. It is not a corporation but it is a legal form of a company. It is a hybrid business structure that can combine the pass-through taxation of a sole proprietorship with the limited liability of a corporation. Regulation of LLCs varies from state to state. I think LLCs also require a payroll, but I’m unsure. I’m not aware of any major benefits of an LLC over an S-Corp, especially if your entire business is only you — a single individual. You most likely do not need an LLC. It is also my understanding that dissolving an LLC is significantly more work than dissolving an S-Corp.

LLCs are easier to set up than an S-Corp 
they also do not require a payroll.

some more reference https://stripe.com/resources/more/s-corp-vs-llc?

> Fewer formalities
> LLCs generally have fewer formalities and reporting requirements than S corps, which can make them easier—and less expensive—to manage.

**Comment by jessesquires** [comment]
Thanks @ljmatkins!

I will update the post!

**Comment by jessesquires** [comment]
post has been updated!
