### ISSUE TITLE
A simple fastlane setup for solo indie developers

### ISSUE THREAD

**Issue by ricardopereira** [jessesquires/jessesquires.com#192]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2024/01/22/fastlane-for-indies/

Hi Jesse, thanks for creating this article. It has great insights about Fastlane. I'm trying to apply some of the tips you shared and I have a question regarding the App Store Connect API key as JSON file. I put the relative path, in my case `~/Development/AppStoreAPIKey.json`, in my Fastfile:

```
pilot(
      team_id: COMPANY_TEAM_ID,
      ipa: PRODUCTION_IPA_PATH,
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      api_key_path: "~/Development/<redacted>.json"
    )
```

but Fastlane raises an issue: `[22:54:44]: Couldn't find API key JSON file at path '~/Development/<redacted>.json'`.

In your case, do you use the full path of the JSON file?

**Comment by jessesquires** [comment]
Thanks @ricardopereira ! 🙌🏼 

I specify the absolute path in my `DeliverFile`

```ruby
api_key_path("/Users/jsq/Developer/AppStoreConnect/api_key.json")
```

**Comment by ricardopereira** [comment]
Nice! Didn't know that.
Thanks for clarifying.
