### ISSUE TITLE
Suggestion: How to fix Mac menu bar icons hidden by the MacBook notch

### ISSUE THREAD

**Issue by thielem** [jessesquires/jessesquires.com#194]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/2023/12/16/macbook-notch-and-menu-bar-fixes/

Hi! 
Thank you for this highly informative post; the commands for setting spacing and padding were very useful to me.

I want to share an additional solution that works very well for me. [Znotch](https://github.com/zkondor/znotch) is a lightweight app that toggles the notch, similar to the app proposed in your blog post. In combination with [Raycast](https://www.raycast.com/), I have set a keyboard shortcut to toggle the notch and find my hidden menu bar items.

**Comment by jessesquires** [comment]
thanks @thielem ! I've updated the post.

**Comment by CanRau** [comment]
Hey @jessesquires, after trying out [HiddenBar](https://github.com/UeharaYou/HiddenBar) thanks to your blog post, but then realizing it doesn't actually help with the notch I stumbled upon [Ice](https://github.com/jordanbaird/Ice), which supports showing the hidden items in a separate "Ice Bar" below the menu bar
