### ISSUE TITLE
JSON Feed double quotes

### ISSUE THREAD

**Issue by nickromano** [jessesquires/jessesquires.com#64]
https://github.com/jessesquires/jessesquires.com/blob/master/feed.json

### Comments, questions, feedback

Thank you for putting an example JSON feed together!  Hope to use this as well.  It looks like there might be one small change needed to parse the JSON.  

```
            "title": "{{ post.title | jsonify }}",
```

Might need to be changed to 

```
            "title": {{ post.title | jsonify }},
```

To prevent the double quotes.

<img width="879" alt="screen shot 2017-09-05 at 2 31 42 pm" src="https://user-images.githubusercontent.com/70799/30084454-49a5b71e-9247-11e7-9497-f8b2162a79e7.png">

Nick

**Comment by jessesquires** [comment]
Oh shit. That's correct. Thanks so much @nickromano ! 🙌

**Comment by jessesquires** [comment]
validated ✅ via https://jsonvalidatortool.com
