### ISSUE TITLE
Swift documentation -- add a link to Part 2 on the original post

### ISSUE THREAD

**Issue by richellis** [jessesquires/jessesquires.com#76]
Feedback: https://www.jessesquires.com/blog/swift-documentation/

I was originally creating this issue to ask you to update the post with your latest process, since you don't seem to be using it anymore for JSQCoreDataKit. But then I found [Part 2](https://www.jessesquires.com/blog/swift-documentation-part-2/)! 😄  So now this is just a suggestion to add a link from the original post to Part 2.

Thanks!

**Comment by jessesquires** [comment]
Thanks @richellis !

Updated!
