### ISSUE TITLE
Enums as configuration: the anti-pattern

### ISSUE THREAD

**Issue by aainaj** [jessesquires/jessesquires.com#82]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/enums-as-configs/

This article clarifies my doubt for open closed principle. But still on idea how to fix this problem?

Let's say I have different types of cells to return in collection view `cellForItem(at:)` function. To identify which cell to return I check enum type of item and return appropriate cell. In this situation how can I get rid of enum here?

**Comment by jessesquires** [comment]
Thanks @aainaj !

The different cell types problem can be tricky. The best/easier thing here might just be a mapping of `model type <--> cell type`. It's hard to say without knowing any details. 😄
