### ISSUE TITLE
How to run sysdiagnose on iOS simulator

### ISSUE THREAD

**Issue by Splaktar** [jessesquires/jessesquires.com#87]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/how-to-sysdiagnose-ios/

Your post is helpful, but I've been asked to provide a "sysdiagnose" for an issue that I reported when I don't haven an iOS device. I haven't been able to find instructions for this process when using an iOS Simulator via Xcode. 

Do you know how to do this?

Thank you.

**Comment by Splaktar** [comment]
Russ Bishop suggested [simctl diagnose](https://mobile.twitter.com/xenadu02/status/1079515391775232000) which gave me `simctl: command not found`.

However, using that I was able to find [this article](https://medium.com/xcblog/simctl-control-ios-simulators-from-command-line-78b9006a20dc) that gave me enough information to try `xcrun simctl diagnose` which did work! This ran the "sysdiagnose" on the Simulator and left the result in `/private/tmp/`.

**Comment by Splaktar** [comment]
Actually, I'm going to leave this open as it would be good to add this information to the article as it's the first one listed when Googling "how to sysdiagnose ios simulator".

**Comment by jessesquires** [comment]
Thanks so much @Splaktar ! 🙌 Really appreciate it.

The post has been updated:
https://www.jessesquires.com/blog/how-to-sysdiagnose-ios/
