### ISSUE TITLE
[Executing AppleScript in a Mac app on macOS Mojave and dealing with AppleEvent sandboxing]

### ISSUE THREAD

**Issue by Fidetro** [jessesquires/jessesquires.com#92]
Hi Jesse,

I saw your article [
Executing AppleScript in a Mac app on macOS Mojave and dealing with AppleEvent sandboxing](https://www.jessesquires.com/blog/executing-applescript-in-mac-app-on-macos-mojave/)

I have same issues,I was successful because of the negligence of the app store reviewers.
but I can't update it on the appstore right now.😢
by the way,my application is help people mock click Xcode simulate location 

Can you find a solution later?
best wishes

**Comment by jessesquires** [comment]
Thanks for the comment @Fidetro ! 🙌 

Maybe I should try to resubmit.
