### ISSUE TITLE
UIKit changes in iOS 9

### ISSUE THREAD

**Issue by paulbruneau** [jessesquires/jessesquires.com#93]
Comments, Questions, Feedback: https://www.jessesquires.com/blog/UIKit-changes-in-iOS-9/

This article is very nice! It's the best source of this information (I don't even remember anyone else noticing that UIKit delegates finally got fixed in iOS 9, but maybe it's just my memory).

But did you know that `CLLocationManager`'s delegate is still `assign` to this day? I can find nothing on the internet regarding that, and there are new iOS devs out there today who have no idea that they would have to manually zero out their delegate references.

I don't know if any other types suffer from this, I only know about `CLLocationManager` because it bit our team this week.

**Comment by jessesquires** [comment]
Thanks for the kind words @paulbruneau ! 🙌 

Good to know about `CLLocationManager` 🤦‍♂

**Comment by paulbruneau** [comment]
Check this out, Apple fixed it in iOS 13!

<img width="692" alt="Screen Shot 2019-06-06 at 4 30 14 PM" src="https://user-images.githubusercontent.com/978400/59064719-f2a71500-8878-11e9-9492-99a1818679d3.png">

**Comment by jessesquires** [comment]
nice! thanks @paulbruneau ! 👏

**Comment by paulbruneau** [comment]
👍 my pleasure, and thanks for the blog post about it! Feel free to close issue any time.
